### ISSUE TITLE
24-month check for older features, some datasets need to be updated

### ISSUE THREAD

**Issue by evamutz** [nasaharvest/crop-mask#183]
In recent testing, 7 datasets failed the `test_all_older_features_have_24_months` test in [integration_test_labeled.py](https://github.com/nasaharvest/crop-mask/blob/master/test/integration_test_labeled.py)

Uganda [22]
open_buildings [22]
digitalearthafrica_eastern  [22]
Ethiopia [22]
Ethiopia_Tigray_2020 [22]         
Malawi_FAO   [22]
Malawi_FAO_corrected [22]

As a temporary fix, the month offset was bumped up to 4 from 3, so the tests could pass, but these features should be updated to have current data.

**Comment by ivanzvonkov** [comment]
Additionally, a clear message in the test illustrating why it might be failing and how to address the failure for real would be super useful.

@evamutz is this an issue you could potentially tackle?
