### ISSUE TITLE
Notebook for area estimation

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/crop-mask#199]
**Context**: Downstream yield models need area estimates from cropland masks.

**Issue**: There is currently no simple way to derive area estimates from the cropland masks produced by this repository. 

**Potential solution**: A Jupyter notebook that 1) downloads a cropland mask from the bucket gs://crop-mask-preds-merged and 2) computes an estimate of cropland area. The notebook should be made so it can run on Colab to eliminate the need for downloading maps locally. Area estimation should follow that same logic as in the change area notebooks: https://github.com/nasaharvest/crop-mask/pull/179. Functions may need to be moved to a common utility file to avoid duplication.

**Comment by ivanzvonkov** [comment]
@cnakalembe how does this look?

@adebowaledaniel Catherine mentioned you are interested in working on this.

**Comment by adebowaledaniel** [comment]
Yes, I will be working on this. :+1: @ivanzvonkov
