### ISSUE TITLE
Cropland mask: Tanzania North

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/crop-mask#202]
Key tasks:
- [x] Verify the quality of Tanzania labels ([set 1](https://collect.earth/collection?projectId=21561), [set 2](https://collect.earth/collection?projectId=21562)) on CEO 
- [x] [Train a model](https://github.com/nasaharvest/crop-mask#training-a-new-model) using Tanzania data for evaluation 
- [x] Use Tanzania model to [create a crop mask](https://github.com/nasaharvest/crop-mask#creating-a-crop-map) for North Tanzania
- [ ] Comments about quality of map from @cnakalembe

**Comment by adebowaledaniel** [comment]
Completed!
View in EE [here](https://code.earthengine.google.com/c1eb414dc28aa6c369073b491fad5c67?hideCode=true)

**Comment by ivanzvonkov** [comment]
Reposting slack message here:
Looks pretty good upon visual inspection
- Water bodies are classified as non-crop
- The crop % seems to be around half which is close to recent [estimates](https://tradingeconomics.com/tanzania/agricultural-land-percent-of-land-area-wb-data.html#:~:text=Agricultural%20land%20(%25%20of%20land%20area)%20in%20Tanzania%20was%20reported,compiled%20from%20officially%20recognized%20sources.)
- Some cropland is missed on the East
- Kilimanjaro is correctly classified as non-crop 🏔️

Looks like many of those missing values you got were in the ocean
I also see a decent amount of ERA5 looking grid artifacts, so next step would be to retrain the model with the skip_ERA5 argument and rerun predictions. This time the data is all already exported so no need to wait for Earth Engine.

**Comment by adebowaledaniel** [comment]
Pull request for the skip_ERA5 model (https://github.com/nasaharvest/openmapflow/issues/66).

**Comment by adebowaledaniel** [comment]
Tanzania North 2019 (skip ERA5) crop mask view [here](https://code.earthengine.google.com/a2df96c0472913afe35ce9590cb1e61d?hideCode=true).

**Comment by ivanzvonkov** [comment]
> Tanzania North 2019 (skip ERA5) crop mask view [here](https://code.earthengine.google.com/a2df96c0472913afe35ce9590cb1e61d?hideCode=true).

The script has an issue: `Line 1: image2 is not defined`

Could you also add both results to the same script so we can compare?

**Comment by adebowaledaniel** [comment]
Sorry about that; here is the updated [link](https://code.earthengine.google.com/285547b2194c1317f131db821204a6a4?hideCode=true).

With both results, you mean with and without ERA5?

**Comment by ivanzvonkov** [comment]
Yes both with and without ERA5

**Comment by adebowaledaniel** [comment]
You can compare both result [here](https://code.earthengine.google.com/a4a4a2517a66c884562252bfe84234ec?hideCode=true)

**Comment by adebowaledaniel** [comment]
@ivanzvonkov The updated comparison view is [here](https://code.earthengine.google.com/261ca0e130d0e29fcf4da3710464e52c?hideCode=true). 
I will mosaic the multiple rasters generated for each model if needed in another issue.

**Comment by ivanzvonkov** [comment]
Excellent! Looks like there are some more fields found in the North East now and a lot fewer grid artifacts. 
I didn't realize that the f1-score is also higher when skipping ERA5! 🤔
https://github.com/nasaharvest/crop-mask/blob/494d1d1d7e21dff64e2fcafe2e12887f6d680e7d/data/models.json#L87

@gabrieltseng @hannah-rae interesting result here!

**Comment by cnakalembe** [comment]
Reviewed and ready to merge with Tanzania South

**Comment by adebowaledaniel** [comment]
> Excellent! Looks like there are some more fields found in the North East now and a lot fewer grid artifacts. I didn't realize that the f1-score is also higher when skipping ERA5! 🤔
> 
> https://github.com/nasaharvest/crop-mask/blob/494d1d1d7e21dff64e2fcafe2e12887f6d680e7d/data/models.json#L87
> 
> @gabrieltseng @hannah-rae interesting result here!

What is the following line of action with this? Is there a conclusion on the performance of with/without ERA5 based on other models trained? Moving forward, which model versions should be used for the final merge of both Tanzania North and South?
