### ISSUE TITLE
Cropland: Tanzania South 2019

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/crop-mask#214]
Key Tasks:
- [x] [Train a model](https://github.com/nasaharvest/crop-mask#training-a-new-model) using Tanzania data from September-September for evaluation by using the `--start_month` parameter
- [x] Use Tanzania model to [create a crop mask](https://github.com/nasaharvest/crop-mask#creating-a-crop-map) for South Tanzania from September 2019 to September 2020

**Comment by ivanzvonkov** [comment]
The bounding box should include South Tanzania including all of the Iringa region

**Comment by adebowaledaniel** [comment]
@ivanzvonkov and @cnakalembe 
Tanzania cropland (2019): [link](https://code.earthengine.google.com/1688b8ab705844208f0d614b0b332853?hideCode=true
)

Tanzania south cropland 2019: 
- [mask](https://code.earthengine.google.com/52ae9d46286af1f8fcb84db305df4263?hideCode=true)
- [metrics](https://github.com/nasaharvest/crop-mask/blob/2b460d324444c6f3e97b54440cfdb86b943b449d/data/models.json#L104-L111)

**Comment by ivanzvonkov** [comment]
@cnakalembe I believe this is waiting for your comment

**Comment by cnakalembe** [comment]
@adebowaledaniel can you make the asset public?

**Comment by adebowaledaniel** [comment]
@cnakalembe, done.

**Comment by cnakalembe** [comment]
Reviewed-- @adebowaledaniel please merge North and South into one map.

**Comment by adebowaledaniel** [comment]
@cnakalembe and @ivanzvonkov 
Here is the link to the merged map [GEE asset ](https://code.earthengine.google.com/?asset=users/adadebay/Tanzania_cropland_2019); upload to the cloud storage is ongoing.

**Comment by ivanzvonkov** [comment]
Remake without ERA5

**Comment by adebowaledaniel** [comment]
Tanzania cropland without ERA5 [final merge](https://code.earthengine.google.com/96bbe7fbe3be18a5cd93ffb738a18793?hideCode=true). @cnakalembe @ivanzvonkov
