### ISSUE TITLE
Cropland: Sudan Blue Nile 2019

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/crop-mask#217]
**Start year:** 2019
**Start month:** February

- [x] Labeling project created (#204)
- [x] Labeling completed
- [x] Data added to repository
- [x] Model trained (#296)
- [x] Map made
- [ ] Expert check

**Comment by ivanzvonkov** [comment]
## Data stats 
https://github.com/nasaharvest/crop-mask/blob/0dc58b8867dbee8fa17fa5131c95e52e97d3fcb3/data/report.txt#L269
```
Sudan_Blue_Nile_CEO_2019 (Timesteps: 24)
----------------------------------------------------------------------------
disagreement: 0.0%
eo_data_complete    1500
✔ training amount: 311, positive class: 31.5%
✔ validation amount: 581, positive class: 37.9%
✔ testing amount: 608, positive class: 37.5%
```
## Test metrics
https://github.com/nasaharvest/crop-mask/blob/0dc58b8867dbee8fa17fa5131c95e52e97d3fcb3/data/models.json#L70
```
"accuracy": 0.9408,
"f1_score": 0.9227,
"precision_score": 0.9034,
"recall_score": 0.943,
"roc_auc_score": 0.9723
```
## Map
https://code.earthengine.google.com/382a613f09d8d435ee0ccd9313bde813
<img width="375" alt="image" src="https://user-images.githubusercontent.com/25067660/201745358-e85e6d11-628b-444e-afa8-c044494b0dc5.png">

## Additional Notes
Initial prediction merging led to some missing tiles, after investigating and remerging same predictions v2 had not missing tiles. Attributing to some intermittent merging issue.

**Comment by ivanzvonkov** [comment]
Related #244

**Comment by cnakalembe** [comment]
Reviewed-- as with others like Tanzania, we seem to have issues around wetlands; otherwise, the mask looks decent. I suggest we look into sourcing non-crop examples of wetlands in CropHarvest possibly from a recent wetland product-- hopefully, one that does well at separating crops like rice.

**Comment by hannah-rae** [comment]
Potential source of global wetland map that we could use, but should cross-check with the "problem areas" where wetlands are misclassified in our map: https://www2.cifor.org/global-wetlands/

**Comment by hannah-rae** [comment]
Another potential wetlands dataset for sampling non-crop points from: https://www.worldwildlife.org/pages/global-lakes-and-wetlands-database

**Comment by ivanzvonkov** [comment]
Next step corrective labeling with GEE script, relevant #222

**Comment by ivanzvonkov** [comment]
Short term -> corrective labeling
Long term -> Issue about wetland data + analysis

**Comment by MsPixels** [comment]
@cnakalembe, please find the link to the Corrective labeling App for Sudan Blue Nile https://aasareansah.users.earthengine.app/view/sudanbluenilecorrectivelabelapp

**Comment by cnakalembe** [comment]
[Sudan Blue Nile_new points.csv](https://github.com/nasaharvest/crop-mask/files/10157985/Sudan.Blue.Nile_new.points.csv)
[](url)

**Comment by ivanzvonkov** [comment]
Second version of map: https://code.earthengine.google.com/1026aec46650a3578d3672b04e34c4d2
Looks about the same

**Comment by cnakalembe** [comment]
It is better in some places. I can do another round of corrective labeling, this time denser than before. The first time I was being conservative, looking for larger patterns.

**Comment by ivanzvonkov** [comment]
Let's discuss on Monday in the meeting!
