### ISSUE TITLE
Cropland: Zambia 2019

### ISSUE THREAD

**Issue by adebowaledaniel** [nasaharvest/crop-mask#221]
**Start year: 2019** 
**Start month: November**

- [x] Labeling project created
- [x] Labeling completed
- [x] Data added to repository
- [x] Model trained (https://github.com/nasaharvest/crop-mask/pull/248/files)
- [x] Map made
- [x] Ideas for improvement @adebowaledaniel
- [x] Expert review @hannah-rae @cnakalembe (map on [GEE](https://code.earthengine.google.com/541c4727c2933d23e54ac0ab43511343))
- [x] Expert check of GLAD map - is 30m map ok for use case of this map? Accuracy is equivalent to ensemble.
- [x] Export best map

**Comment by adebowaledaniel** [comment]
@cnakalembe, can you confirm the start month (February or September)?

**Comment by ivanzvonkov** [comment]
Merging script: https://github.com/nasaharvest/openmapflow/blob/main/openmapflow/scripts/merging.sh

**Comment by adebowaledaniel** [comment]
@ivanzvonkov, there are missing predictions in the Zambia cropland mask see [here](https://code.earthengine.google.com/a9522bd391a18cd98268994b6bffe317?hideCode=true); despite running the inference multiple times which gave the same number of predictions made see the screenshot below.
![image](https://user-images.githubusercontent.com/20906703/197235216-e492a315-2520-4774-9f4b-5b89c0c75f38.png)

**Comment by ivanzvonkov** [comment]
I think this is most likely due to the nan values in some tifs, you can go ahead and merge. 
The logs can be investigated to find out why this is happening

**Comment by adebowaledaniel** [comment]
I already merged; see the link I provided above (https://code.earthengine.google.com/a9522bd391a18cd98268994b6bffe317?hideCode=true)

The [error messages](https://cloudlogging.app.goo.gl/ek3w4dhYSrrGoEGj8) vary; one is a request timeout, and the other is not specific.

**Comment by ivanzvonkov** [comment]
Some of the errors I am seeing look like this
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/25067660/197607687-e4a18de0-9293-4956-b009-f89630bb0469.png">

This means there's a nan value in the tif. This was fixed in a newer version of OpenMapFlow (https://github.com/nasaharvest/openmapflow/pull/109)

It'll be deployed if you install it manually before deployment
```bash
pip install openmapflow==0.2.1rc2
export OPENMAPFLOW_MODELS="..."
openmapflow deploy
```

**Comment by ivanzvonkov** [comment]
New version can now be deployed if it's on master here: https://github.com/nasaharvest/crop-mask/actions/workflows/deploy.yml

**Comment by adebowaledaniel** [comment]
[EE link](https://code.earthengine.google.com/36bd39fd129eb3e528526d58cb1638ad?asset=projects%2Fearthengine-legacy%2Fassets%2Fusers%2Fadadebay%2FZambia_2019_min_lat--18-12_min_lon-21-93_max_lat--8-15_max_lon-33-77_dates-2019-11-01_2020-11-01_v2&hideCode=true)

**Comment by ivanzvonkov** [comment]
- Look into logs for what bands have Nans the most
- Skip those in the training of the next model

**Comment by ivanzvonkov** [comment]
Blocked by #230

**Comment by ivanzvonkov** [comment]
Above is merged can retrain with missing values in training data

**Comment by adebowaledaniel** [comment]
Here is the error I got while trying to retrain the model @ivanzvonkov. 

![image](https://user-images.githubusercontent.com/20906703/203182043-3fc45fde-770f-41ce-a1d9-c9a826518f62.png)

**Comment by adebowaledaniel** [comment]
Nit: I think this warning might be of concern later.

![image](https://user-images.githubusercontent.com/20906703/203183369-c85d0650-db97-4481-a3a1-386d04a040de.png)

**Comment by ivanzvonkov** [comment]
@adebowaledaniel re: arrow error it happens because of this line
https://github.com/nasaharvest/crop-mask/blob/7f5f809149d49aea9458e13d5ee88d3ad3b3484b/src/models/data.py#L95

Do you see the bug? 🐛

**Comment by adebowaledaniel** [comment]
Yes, I see that....

**Comment by ivanzvonkov** [comment]
#248 will be merged soon

**Comment by ivanzvonkov** [comment]
Consider creating small map and checking visually

**Comment by adebowaledaniel** [comment]
Still the same problem @ivanzvonkov 
![image](https://user-images.githubusercontent.com/20906703/209740693-c9625a81-3fff-457a-b8f0-5fb8385c3e99.png)

**Comment by hannah-rae** [comment]
@adebowaledaniel to investigate a few things to debug:
-  check the GEE logs to see if there are any errors being thrown to explain why there is missing data 
- run error analysis notebook to plot errors in evaluation set to see if there is geographical pattern to errors (may need to update notebook)

**Comment by adebowaledaniel** [comment]
The three error codes in the logs:
1. [500](https://cloud.google.com/run/docs/troubleshooting#abort-request): The request was aborted because there was no available instance. As a result of (i) a sudden increase in traffic or (ii) long request processing time.
2. [503](https://cloud.google.com/run/docs/troubleshooting#malformed-response-or-connection-error): The request failed because either the HTTP response was malformed or connection to the instance had an error. The container instance was found to be using too much memory and was terminated. This is likely to cause a new container instance to be used for the next request to this revision.
3. [504](https://cloud.google.com/run/docs/configuring/request-timeout): The request has been terminated because it has reached the maximum request timeout.

**Potential solution**: Increasing the memory limit and reducing the request per container.

**Comment by adebowaledaniel** [comment]
EE link: https://code.earthengine.google.com/5b8618b5e74bf921ddb21d355b217c08

**Comment by ivanzvonkov** [comment]
- error analysis notebook updates
- ERA5 grid overlay on map
- If possible export grid overlay on map

**Comment by ivanzvonkov** [comment]
Ivan to send Zambia data if he has it
Adebowale to create PR for error analysis notebook update

**Comment by adebowaledaniel** [comment]
From the [error analysis](https://colab.research.google.com/drive/1DhxFNwqajhpkbyYLqy4GcVgGTUwFJUn1?usp=sharing), lots of the error is due to shrubs, points with lots of vegetation and fallow field predicted as cropland. Also, a point on a rooftop is predicted as a cropland pixel; checking the [prediction map](https://code.earthengine.google.com/5b8618b5e74bf921ddb21d355b217c08), I noticed this pattern which predominantly affects almost the entire city of Lusaka (an urban settlement) to be predicted as cropland.
![image](https://user-images.githubusercontent.com/20906703/229425069-6c6283d9-344d-4898-81ed-7ae72f9aaeca.png)

**Comment by adebowaledaniel** [comment]
Training on higher-quality data; there is no improvement in the new model @hannah-rae 
https://github.com/nasaharvest/crop-mask/blob/853344e17a9e16054a9531840e9752b9b4a1ca00/data/models.json#L310-L312
previous model: https://github.com/nasaharvest/crop-mask/blob/9171bd68b8d86c7acfb2c245b864539b419639fd/data/models.json#L242-L244

**Comment by hannah-rae** [comment]
Next step: evaluate quality of CEO Zambia data (using rubric)

**Comment by hannah-rae** [comment]
Next step for week of May 22 @adebowaledaniel : apply post-classification NDVI filtering (using method designed by @bhyeh ) and evaluate error rates and types

**Comment by hannah-rae** [comment]
During the operational meeting @bhyeh mentioned that @adebowaledaniel noted that since the Zambia_CEO_2019 dataset had a 0/0.5/0.5 train/val/test split the model may not have been trained with any points from Zambia. We usually set the CEO datasets with this ratio when we assume/know there are local samples in the other datasets (e.g. a ground-based dataset independent from the CEO dataset), but in the case of Zambia it's very possible there were little to no points in the other datasets. (One could check in GeoWiki how many are in Zambia, but this is probably the only dataset that has Zambia points). @adebowaledaniel can you post your updated results/plan based on your 0.6/0.2/0.2 split here?

**Comment by adebowaledaniel** [comment]
Thank you, @hannah-rae. As you mentioned, the Geowiki is the only dataset with Zambia data with a training subset with 336 sample points (positive class: 5.6%). Here is the result for the split to 0.6/0.2/0.2. 
https://github.com/nasaharvest/crop-mask/blob/1785602602d1260edb53a13a608e9ee84c5d6f8d/data/models.json#L325-L341

I applied the post-classification NDVI filtering method by Ben on a subset produced by the model; the output is [here](https://code.earthengine.google.com/9d8c57104fc3aa8fa2657fcdfdb97e44).

**Comment by adebowaledaniel** [comment]
June 5 - Check for cloud presence in the tif files

**Comment by hannah-rae** [comment]
Very interesting... was that not captured in the logs at all? Maybe we should add a test when the data are exported to check that none of the bands are missing data. 

For now, perhaps it makes sense to train a new model without S1?

**Comment by adebowaledaniel** [comment]
Here are the outputs of the new model trained without S1: [map](https://code.earthengine.google.com/33946b0e0c6e73cc76704a8ca4ad70c3)(as expected, it's without the weird features) and [metrics](https://github.com/nasaharvest/crop-mask/blob/1e9650cfae71c014d6cbd01327f4e69bd7cd9e0f/data/models.json#L359-L373).
Let me know your observation of the subset map generated. Should we continue with this model for the entire country?


I will create an issue regarding the missing S1 bands; also, check the eo export log for any clues.

**Comment by adebowaledaniel** [comment]
@hannah-rae Crop Mask + Postclassification processing: [here](https://code.earthengine.google.com/541c4727c2933d23e54ac0ab43511343)

**Comment by hannah-rae** [comment]
@adebowaledaniel can you make the assets public?

**Comment by adebowaledaniel** [comment]
Done @hannah-rae

**Comment by hannah-rae** [comment]
Loading is crashing for me. @cnakalembe to try loading and will do expert sign-off

**Comment by cnakalembe** [comment]
I reviewed the map; I think the next step is manual cleanup removing obvious features like roads, I've seen some mines too. We could develop some clear guidance for this and I think Diana can do it in QGIS/ArcGIS

**Comment by hannah-rae** [comment]
@hannah-rae will make GEE script in repo to export ensemble map for Zambia (and other future countries)

**Comment by hannah-rae** [comment]
@ivanzvonkov will make this map and update intercomparison re #346

**Comment by ivanzvonkov** [comment]
After running intercomparison on Zambia with full evaluation set (validation and test), ensemble ties the glad map.
![image](https://github.com/nasaharvest/crop-mask/assets/25067660/39ff0664-a57a-4f22-a88d-f20723f0dc09)

There are also not that many points to begin with because many of them were sampled outside of Zambia boundaries (old CEO project).
Should we proceed with just exporting GLAD map?

**Comment by hannah-rae** [comment]
Next step for @cnakalembe to check if the GLAD map looks ok and is ok for use case, or if there is some reason to export the ensemble map instead.

**Comment by hannah-rae** [comment]
Next step: @ivanzvonkov run the export code for GLAD map

**Comment by ivanzvonkov** [comment]
Shared exported map on slack
