### ISSUE TITLE
Cropland: Sudan Blue Nile 2020

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/crop-mask#234]
**Start year:** 2020
**Start month:** February

- [x] Labeling project created
- [x] Set 1 Labeling
- [x] [Set 2](https://app.collect.earth/collection?projectId=33434) Labeling: Sheila, Ben, Diana, Alana, Bhanu, Aninda, Taryn
- [x] Data added to repository @MsPixels 
- [x] Model trained @adebowaledaniel 
- [x] Map made @ivanzvonkov 
- [x] Expert check

**Comment by ivanzvonkov** [comment]
@MsPixels here's an alternative task you can consider while the environment issues get resolved.
The first part here is to add a labeling project, the instructions are here: https://github.com/nasaharvest/crop-mask/blob/master/notebooks/random_sample_from_shapefile_ceo.ipynb
I made you admin on CEO so you can add projects!

**Comment by MsPixels** [comment]
@ivanzvonkov, attempts to submit a pull request to this repo has failed. This is the message that keeps popping up "permission to nasaharvest/crop-mask.git has been denied"

**Comment by ivanzvonkov** [comment]
You were able to open a PR here before: https://github.com/nasaharvest/crop-mask/pull/232
So I think the account has access, I feel that it's not logged in properly. Is this in the colab notebook?

**Comment by MsPixels** [comment]
Alright sure. Yes, it's in the colab notebook

**Comment by ivanzvonkov** [comment]
Map v1: https://code.earthengine.google.com/b5bab28cc2d08fe28857fac6cb723e3a?asset=projects%2Fearthengine-legacy%2Fassets%2Fusers%2Fizvonkov%2FSudan_Blue_Nile_2020

**Comment by hannah-rae** [comment]
It looks good to me. I am marking done for now but can re-consider if @cnakalembe strongly disagrees.
