### ISSUE TITLE
Cropland: Sudan Al Gadaref 2019

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/crop-mask#235]
**Start year:** 2019
**Start month:** February

- [x] Labeling project created
- [x] Labeling completed
- [x] Data added to repository
- [x] Model trained
- [x] Map made

**Comment by MsPixels** [comment]
Hello @hannah-rae, done training the model. The test metrics is here: 

"accuracy": 0.8735,
"f1_score": 0.8459,
"precision_score": 0.8194,
"recall_score": 0.8741,
"roc_auc_score": 0.9432

**Comment by hannah-rae** [comment]
@MsPixels will make the map this week!

**Comment by MsPixels** [comment]
Created the map [here](https://code.earthengine.google.com/3df4f7ea6088033831ed054a639c43f1?asset=projects%2Fearthengine-legacy%2Fassets%2Fusers%2Fabaansah%2FSudan_Al_Gadaref_2019). However, it observed that some of the forested areas were captured as croplands in the mask.
