### ISSUE TITLE
Cropland: Tigray Ethiopia 2020

### ISSUE THREAD

**Issue by hannah-rae** [nasaharvest/crop-mask#252]
**Start year:** 2020
**Start month:** February

- [x] Labeling project created
- [x] Labeling completed
- [x] Data added to repository
- [x] Model trained
- [x] Map made
- [x] Expert check

**Comment by hannah-rae** [comment]
The labels for validation/test for this have already been completed last year. The data associated with the labels has been exported too, but I think we should re-export them since there have been changes since the last time it was done. @ivanzvonkov do you agree?

**Comment by ivanzvonkov** [comment]
Yes you can see the data that is already available here:
https://github.com/nasaharvest/crop-mask/blob/74913ceff6b4bc4c3fd88f0aa3a381043108ffc9/data/report.txt#L132

The csv files can be accessed by running the following inside a cloned repo
```bash
dvc pull data/datasets
```
The data has been updated according to various changes over the last year. One outstanding change is using data with nans instead of skipping it. This can be achieved by 
First, deleting the csv from `data/datasets` 
Then
```bash
dvc commit data/datasets 
dvc push
git add .
git commit -m'Update data'
git push
```
This will run the data pipeline and automatically generated new csvs with missing data not skipped.

**Comment by hannah-rae** [comment]
Model is trained, pending merge of #266

**Comment by bhyeh** [comment]
[first map draft](https://code.earthengine.google.com/34d292378011d63a822c1e852b59745c?asset=projects%2Fearthengine-legacy%2Fassets%2Fusers%2Fby253%2Fby253)

- something funky? does not capture entire Tigray state

**Comment by bhyeh** [comment]
Retrain model without ERA5 data. Middle artifacts present in above seem to be in line with ERA5 sized tiling - Dr. Kerner

**Comment by bhyeh** [comment]
Retrained 2020 model without ERA5 data. Changed testing and validation metrics [here](https://github.com/nasaharvest/crop-mask/compare/master...ethiopia_tigray_2020#diff-6f20f0a82b5f74a0c813b457679c394513096c3bc86ff2e4a5eb71a41842ab42)

**Comment by ivanzvonkov** [comment]
@bhyeh is the new map ready for review? Does it have artifacts and/or missing data?

**Comment by bhyeh** [comment]
[Here](https://code.earthengine.google.com/23fb657daf75049df3fd742cb9edf974?asset=projects%2Fearthengine-legacy%2Fassets%2Fusers%2Fbyeh1%2Fethiopia_tigray_2020_v4) is a link for the latest map for 2020. Was having issues with missing predictions the last few tries - but all is well now!

**Comment by MsPixels** [comment]
Yes @hannah-rae, I can set it up for @bhyeh

**Comment by MsPixels** [comment]
@bhyeh, Corrective labeling for Tigray 2020](https://aasareansah.users.earthengine.app/view/corrective-labeling-tigray-feb-2020-2021). More resources can also be found [here](https://github.com/nasaharvest/crop-mask/wiki/Corrective-Labeling)

**Comment by hannah-rae** [comment]
Next step: @bhyeh to make updated Tigray 2020 map with model updated with corrective labels
