### ISSUE TITLE
Cropland: Uganda 2019

### ISSUE THREAD

**Issue by adebowaledaniel** [nasaharvest/crop-mask#254]
**Start year:**  2019
**Start month:** February

- [x] Labeling project created
- [x] Labeling completed
- [x] Data added to repository
- [x] Model trained
- [x] Map made
- [ ] Expert check

**Comment by adebowaledaniel** [comment]
View map on [Earth Engine](https://code.earthengine.google.com/cfa1590779c2021055f35aaa5976857e?asset=projects%2Fearthengine-legacy%2Fassets%2Fusers%2Fadadebay%2FUganda_2019_skip_ERA5_min_lat--1-63_min_lon-29-3_max_lat-4-3_max_lon-35-17_dates-2019-02-01_2020-02-).

**Comment by cnakalembe** [comment]
Also, put this one up for corrective labeling. I see a lot of cropland in wetland areas that we missed.
