### ISSUE TITLE
Framework-diagram

### ISSUE THREAD

**Issue by cnakalembe** [nasaharvest/crop-mask#285]
![Nakalembe_GLAM-B](https://user-images.githubusercontent.com/9597566/225414376-ad337cf9-df03-4c4d-b641-7ccc8ad175bf.png)

**Comment by ivanzvonkov** [comment]
Why was this created??

**Comment by hannah-rae** [comment]
@cnakalembe Are there any actions associated with this issue? Can it be closed if not?
