### ISSUE TITLE
Cropland: Senegal March 2022

### ISSUE THREAD

**Issue by cnakalembe** [nasaharvest/crop-mask#312]
- [x] Labeling projects created and links added below
- [ ] [Set 1](https://app.collect.earth/collection?projectId=35160) Labeling
- [ ] [Set 2](https://app.collect.earth/collection?projectId=35161) Labeling
- [ ] [Set 3](https://app.collect.earth/collection?projectId=35277) Labeling
- [ ] Data added to repository
- [ ] Model trained
- [ ] Map made
- [ ] Expert check

**Comment by adebowaledaniel** [comment]
Duplicate of #315
